services:
  elasticsearch:
    build:
      context: .
      dockerfile: elastic-icu-8.16.1.Dockerfile
    container_name: uwazi-elasticsearch
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    environment:
      - bootstrap.memory_lock=true
      - indices.query.bool.max_clause_count=2048
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms2g -Xmx2g'
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - uwazi_network

  mongo:
    image: 'mongo:8'
    container_name: uwazi-mongo
    command: mongod --replSet "uwazi_replica_set"
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - uwazi_network

  mongoreplicaset_start_script:
    image: "mongo:8"
    restart: "no"
    container_name: mongoreplicaset_start_script
    depends_on:
      - mongo
    entrypoint: [ "bash", "-c", "sleep 10 && mongosh --host mongo:27017 --eval 'rs.initiate();cfg = rs.config(); cfg.members[0].host = \"mongo:27017\";rs.reconfig(cfg, {force:true})'"]
    networks:
      - uwazi_network

  redis:
    image: 'redis:7'
    container_name: uwazi-redis
    command: redis-server
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - uwazi_network

  minio:
    image: minio/minio
    container_name: uwazi-s3
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage/minio:/data
    command: server /data --console-address :9001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL http://localhost:9000/minio/health/live || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - uwazi_network

  uwazi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uwazi-app
    depends_on:
      - mongo
      - mongoreplicaset_start_script
      - elasticsearch
      - redis
      - minio
    environment:
      - DATABASE_HOST=mongo
      - DATABASE_NAME=uwazi_development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - IS_FIRST_DEMO_RUN=false
      - INDEX_NAME=uwazi_development
      - FILES_ROOT_PATH=/uwazi/
      - USE_ELASTIC_ICU=true
    ports:
      - '3000:3000'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsSL http://localhost:3000 || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - uwazi_network

volumes:
  esdata01:
    driver: local
  mongodata:
    driver: local

networks:
  uwazi_network: